config:
  extends: ../../.markdownlint.yaml
  MD041: false
  agent-frontmatter-fields:
    required_fields:
      - name
      - description
      - model

globs:
  - "**/*.md"

customRules:
  - "./agent-frontmatter.cjs"
