netrc:
  url: https://gitlab.com
  token: glpat-xxxxxxx

proxy:
  enabled: false
  http: http://proxy.example.com:8080
  https: https://proxy.example.com:8080
  noProxy: example.com

installAdditionalDeps:
  kubernetes: false
  azure: false
