netrc:
  machines:
    - url: https://gitlab.com
      username: __token__
      token: glpat-xxxxxxx
    - url: https://github.com
      username: __token__
      token: ghp_xxxxxxx

proxy:
  enabled: false
  http: http://proxy.example.com:8080
  https: https://proxy.example.com:8080
  noProxy: example.com

installAdditionalDeps:
  python: true
  kubernetes: false
  azure: false
