version: 2

project_name: dotfiles

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    main: .
    binary: dotfiles
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: darwin
    main: .
    binary: dotfiles
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: dotfiles
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end -}}
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: lvlcn-t
    name: dotfiles
