[git]
autoCommit = true
autoPush = false
commitMessageTemplate = "{{ promptString \"Commit message\" }}"

[edit]
command = "code"
args = "--wait"

[data.netrc]
[[data.netrc.machines]]
url = "https://gitlab.com"
username = "__token__"
token = "glpat-xxxxxxx"

[[data.netrc.machines]]
url = "https://github.com"
username = "__token__"
token = "ghp_xxxxxxx"

[data.machine.proxy]
enabled = false
http = "http://proxy.example.com:8080"
https = "https://proxy.example.com:8080"
noProxy = "example.com"
